# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "cent64-64bit"
  config.vm.box_url = "http://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.4-x86_64-v20130427.box"
  config.vm.network :private_network, ip: "192.168.33.10"

  config.vm.synced_folder "../../path/to/your/symfony/project", "/var/www/project"

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "../../"
    chef.roles_path = "../../roles"
    chef.data_bags_path = "../../data_bags"
    chef.add_recipe("hishida_dev::vagrant")

    #php5.4系の場合
    chef.json = {
      "php_ver" => "54"
    }

    #php5.3系の場合
    #chef.json = {
    #  "php_ver" => "53"
    #}
  end
end
